# Generated by Django 6.0.1 on 2026-01-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table='books_table',
        ),
    ]
